# Чтобы установить тему оформления нужно ереименовать _config.txt в _config.yml  

theme: jekyll-theme-minimal
title: [ABC Unix]
description: [Администрирование Вычислительных Сетей на основе операционных систем семейства Unix]
